theme: jekyll-theme-slate
title: Romanian Dvorak Keyboard Layout
description: Dvorak implementation for Romanian with proper diacritics.
show_downloads: true
github:
  zip_url: https://github.com/thelightstain/romanian-dvorak-keyboard-layout/tree/main/dist/windows/ro-dv.zip
